service: nodejs-api

custom:
  table: examples-table-projection
  region: eu-west-2

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage}
  region: "${self:custom.region}"
  logRetentionInDays: 1
  versionFunctions: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:DescribeTable
          Resource:
            - Fn::GetAtt:
              - ExamplesProjectionTable
              - Arn 

  environment:
    STAGE: ${opt:stage}
    REGION: "${self:custom.region}"
    PROJECTION_TABLE: "${self:custom.table}"
    NODE_OPTIONS: --require tracing

functions:
  create:
    handler: post.handler
    events:
      - http:
          path: /
          method: post
  read:
    handler: get.handler
    events:
      - http:
          path: /{id}
          method: get

resources:
  Resources:
    ExamplesProjectionTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: "${self:custom.table}"
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
